In [1]:
import pandas as pd
df = pd.read_csv("Resources/COVID-19_Cases__Tests__and_Deaths_by_ZIP_Code.csv")
df.head()

,ZIP Code,Week Number,Week Start,Week End,Cases - Weekly,Cases - Cumulative,Case Rate - Weekly,Case Rate - Cumulative,Tests - Weekly,Tests - Cumulative,...,Test Rate - Cumulative,Percent Tested Positive - Weekly,Percent Tested Positive - Cumulative,Deaths - Weekly,Deaths - Cumulative,Death Rate - Weekly,Death Rate - Cumulative,Population,Row ID,ZIP Code Location
0,60603,10,03/01/2020,03/07/2020,NaN,NaN,NaN,NaN,0.0,0,...,0.0,0.0,0.0,0,0,0.0,0.0,1174,60603-2020-10,POINT (-87.625473 41.880112)
1,60603,11,03/08/2020,03/14/2020,NaN,NaN,NaN,NaN,0.0,0,...,0.0,0.0,0.0,0,0,0.0,0.0,1174,60603-2020-11,POINT (-87.625473 41.880112)
2,60603,12,03/15/2020,03/21/2020,NaN,NaN,NaN,NaN,1.0,1,...,85.2,0.0,0.0,0,0,0.0,0.0,1174,60603-2020-12,POINT (-87.625473 41.880112)
3,60603,13,03/22/2020,03/28/2020,NaN,NaN,NaN,NaN,3.0,4,...,340.7,0.0,0.0,0,0,0.0,0.0,1174,60603-2020-13,POINT (-87.625473 41.880112)
4,60603,14,03/29/2020,04/04/2020,NaN,NaN,NaN,NaN,6.0,10,...,851.8,0.0,0.0,0,0,0.0,0.0,1174,60603-2020-14,POINT (-87.625473 41.880112)